### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.iot.device.exceptions.ConnectionFailedError
  fullName: azure.iot.device.exceptions.ConnectionFailedError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - inheritance:
          - type: builtins.object
          type: builtins.BaseException
        type: builtins.Exception
      type: azure.iot.device.common.chainable_exception.ChainableException
    type: azure.iot.device.exceptions.ClientError
  langs:
  - python
  module: azure.iot.device.exceptions
  name: ConnectionFailedError
  source:
    id: ConnectionFailedError
    path: azure-iot-device\azure\iot\device\exceptions.py
    remote:
      branch: master
      path: azure-iot-device\azure\iot\device\exceptions.py
      repo: https://github.com/Azure/azure-iot-sdk-python
    startLine: 32
  summary: Failed to establish a connection
  syntax:
    content: ConnectionFailedError(message=None, cause=None)
  type: class
  uid: azure.iot.device.exceptions.ConnectionFailedError
references: []
