### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError
  fullName: azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - type: builtins.object
        type: builtins.BaseException
      type: builtins.Exception
    type: azure.iot.device.common.chainable_exception.ChainableException
  langs:
  - python
  module: azure.iot.device.iothub.auth.iotedge_authentication_provider
  name: IoTEdgeError
  source:
    id: IoTEdgeError
    path: azure-iot-device\azure\iot\device\iothub\auth\iotedge_authentication_provider.py
    remote:
      branch: master
      path: azure-iot-device\azure\iot\device\iothub\auth\iotedge_authentication_provider.py
      repo: https://github.com/Azure/azure-iot-sdk-python
    startLine: 23
  syntax:
    content: IoTEdgeError(message=None, cause=None)
  type: class
  uid: azure.iot.device.iothub.auth.iotedge_authentication_provider.IoTEdgeError
references: []
