### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2019_02_01.models.error_details_py3.ErrorDetails
  fullName: azure.mgmt.network.v2019_02_01.models.error_details_py3
  langs:
  - python
  module: azure.mgmt.network.v2019_02_01.models.error_details_py3
  name: error_details_py3
  source:
    id: error_details_py3
    path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error_details_py3.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error_details_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2019_02_01.models.error_details_py3
references:
- fullName: azure.mgmt.network.v2019_02_01.models.error_details_py3.ErrorDetails
  isExternal: false
  name: ErrorDetails
  parent: azure.mgmt.network.v2019_02_01.models.error_details_py3
  uid: azure.mgmt.network.v2019_02_01.models.error_details_py3.ErrorDetails
